/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Home = {
	_id: string;
	_type: 'home';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	publishedAt?: string;
	headerSection?: CtaSection;
};

export type Blog = {
	image: any;
	_id: string;
	_type: 'blog';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	author?: string;
	publishedAt?: string;
	tags?: Array<string>;
	excerpt?: string;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'imageWithAlt';
	};
	body?: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
				listItem?: 'bullet';
				markDefs?: Array<
					| {
							href?: Link;
							_type: 'link';
							_key: string;
					  }
					| ({
							_key: string;
					  } & TextColor)
					| ({
							_key: string;
					  } & HighlightColor)
				>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| ({
				_key: string;
		  } & Button)
		| {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
				_key: string;
		  }
		| {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
				};
				media?: unknown;
				_type: 'file';
				_key: string;
		  }
	>;
};

export type FaqSection = {
	_type: 'faqSection';
	sectionTitle?: string;
	title?: string;
	faqs?: Array<
		{
			_key: string;
		} & Faq
	>;
};

export type CtaSection = {
	_type: 'ctaSection';
	backgroundImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'imageWithAlt';
	};
	title?: string;
	description?: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
				listItem?: 'bullet';
				markDefs?: Array<
					| {
							href?: Link;
							_type: 'link';
							_key: string;
					  }
					| ({
							_key: string;
					  } & TextColor)
					| ({
							_key: string;
					  } & HighlightColor)
				>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| ({
				_key: string;
		  } & Button)
		| {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
				_key: string;
		  }
		| {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
				};
				media?: unknown;
				_type: 'file';
				_key: string;
		  }
	>;
	button?: Button;
};

export type ContactSection = {
	_type: 'contactSection';
	title?: string;
	contactMethods?: Array<{
		type?: 'email' | 'phone' | 'address' | 'social';
		label?: string;
		value?: string;
		link?: Link;
		_key: string;
	}>;
};

export type ImageWithAlt = {
	_type: 'imageWithAlt';
	asset?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
	};
	media?: unknown;
	hotspot?: SanityImageHotspot;
	crop?: SanityImageCrop;
	alt?: string;
};

export type Faq = {
	_type: 'faq';
	question?: string;
	answer?: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
				listItem?: 'bullet';
				markDefs?: Array<
					| {
							href?: Link;
							_type: 'link';
							_key: string;
					  }
					| ({
							_key: string;
					  } & TextColor)
					| ({
							_key: string;
					  } & HighlightColor)
				>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| ({
				_key: string;
		  } & Button)
		| {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
				_key: string;
		  }
		| {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
				};
				media?: unknown;
				_type: 'file';
				_key: string;
		  }
	>;
};

export type Button = {
	_type: 'button';
	text?: string;
	link?: Link;
};

export type Navbar = {
	_id: string;
	_type: 'navbar';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	links?: Array<{
		text?: string;
		link?: Link;
		sublinks?: Array<{
			type?: 'auto' | 'tag' | 'manual';
			pageType?: 'custom' | 'blog';
			text?: string;
			link?: Link;
			tagFilter?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'tag';
			};
			tagPageType?: 'custom' | 'blog';
			_key: string;
		}>;
		_key: string;
	}>;
};

export type Tag = {
	_id: string;
	_type: 'tag';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	description?: string;
};

export type Settings = {
	_id: string;
	_type: 'settings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	longTitle?: string;
	websiteName?: string;
	description?: string;
	logo?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	favicon?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	footer?: string;
};

export type BlockContent = Array<
	| {
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: 'span';
				_key: string;
			}>;
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
			listItem?: 'bullet';
			markDefs?: Array<
				| {
						href?: Link;
						_type: 'link';
						_key: string;
				  }
				| ({
						_key: string;
				  } & TextColor)
				| ({
						_key: string;
				  } & HighlightColor)
			>;
			level?: number;
			_type: 'block';
			_key: string;
	  }
	| ({
			_key: string;
	  } & Button)
	| {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
			_key: string;
	  }
	| {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
			};
			media?: unknown;
			_type: 'file';
			_key: string;
	  }
>;

export type HighlightColor = {
	_type: 'highlightColor';
	label?: string;
	value?: string;
};

export type TextColor = {
	_type: 'textColor';
	label?: string;
	value?: string;
};

export type SimplerColor = {
	_type: 'simplerColor';
	label?: string;
	value?: string;
};

export type MetaTag = {
	_type: 'metaTag';
	metaAttributes?: Array<
		{
			_key: string;
		} & MetaAttribute
	>;
};

export type MetaAttribute = {
	_type: 'metaAttribute';
	attributeKey?: string;
	attributeType?: 'string' | 'image';
	attributeValueImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	attributeValueString?: string;
};

export type SeoMetaFields = {
	_type: 'seoMetaFields';
	nofollowAttributes?: boolean;
	metaTitle?: string;
	metaDescription?: string;
	metaImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	seoKeywords?: Array<string>;
	openGraph?: OpenGraph;
	additionalMetaTags?: Array<
		{
			_key: string;
		} & MetaTag
	>;
	twitter?: Twitter;
};

export type Twitter = {
	_type: 'twitter';
	cardType?: string;
	creator?: string;
	site?: string;
	handle?: string;
};

export type OpenGraph = {
	_type: 'openGraph';
	url?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	title?: string;
	description?: string;
	siteName?: string;
};

export type Custom = {
	_id: string;
	_type: 'custom';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	tags?: Array<string>;
	publishedAt?: string;
	body?: BlockContent;
};

export type Link = {
	_type: 'link';
	text?: string;
	type?: string;
	internalLink?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'custom';
	};
	url?: string;
	email?: string;
	phone?: string;
	value?: string;
	blank?: boolean;
	parameters?: string;
	anchor?: string;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type AllSanitySchemaTypes =
	| Home
	| Blog
	| FaqSection
	| CtaSection
	| ContactSection
	| ImageWithAlt
	| Faq
	| Button
	| Navbar
	| Tag
	| Settings
	| BlockContent
	| HighlightColor
	| TextColor
	| SimplerColor
	| MetaTag
	| MetaAttribute
	| SeoMetaFields
	| Twitter
	| OpenGraph
	| Custom
	| Link
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageHotspot
	| SanityImageCrop
	| SanityFileAsset
	| SanityImageAsset
	| SanityImageMetadata
	| Geopoint
	| Slug
	| SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
